test

diff --git a/.github/workflows/ros-ci.yml b/.github/workflows/ros-ci.yml
--- a/.github/workflows/ros-ci.yml
+++ b/.github/workflows/ros-ci.yml
@@ -1,14 +1,18 @@
+# The name of the workflow
 name: CI
 
+# Specifies the events that trigger the workflow
 on:
   push:
-    branches: [ humble, jazzy, main ]
+    branches: [ main, humble, jazzy ]
   pull_request:
-    branches: [ humble, jazzy, main ]
+    branches: [ main, humble, jazzy ]
 
+# Defines a set of jobs to be run as part of the workflow
 jobs:
+  # The name of the job
   ROS_CI:
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
@@ -45,13 +49,32 @@ jobs:
         with:
           required-ros-distributions: ${{ matrix.ros_distribution }}
 
+      - name: Check and Install ROS dependencies
+        shell: bash
+        run: |
+          set -e
+          source /opt/ros/${{ matrix.ros_distribution }}/setup.bash
+          echo "--- Updating rosdep definitions ---"
+          rosdep update
+          echo "--- Installing system dependencies for ROS 2 ${{ matrix.ros_distribution }} ---"
+          rosdep install --from-paths ros_ws/src --ignore-src -y -r --rosdistro ${{ matrix.ros_distribution }}
+          echo "--- Performing rosdep check for ROS 2 ${{ matrix.ros_distribution }} ---"
+          if rosdep check --from-paths ros_ws/src --ignore-src --rosdistro ${{ matrix.ros_distribution }}; then
+            echo "--- rosdep check passed ---"
+          else
+            echo "--- rosdep check failed: Missing system dependencies or unresolvable keys. ---"
+            exit 1
+          fi
+
       - name: Build and Test
         uses: ros-tooling/action-ros-ci@v0.3
-        env:
-          PIP_BREAK_SYSTEM_PACKAGES: "1"
         with:
           target-ros2-distro: ${{ matrix.ros_distribution }}
-          vcs-repo-file-url: ""
+          vcs-repo-file-url: "https://raw.githubusercontent.com/ROBOTIS-GIT/turtlebot3_home_service_challenge/main/turtlebot3_home_service_challenge_ci.repos"
           package-name: |
-            turtlebot3_dqn
-            turtlebot3_machine_learning
+            turtlebot3_home_service_challenge
+            turtlebot3_home_service_challenge_aruco
+            turtlebot3_home_service_challenge_core
+            turtlebot3_home_service_challenge_manipulator
+            turtlebot3_home_service_challenge_simulation
+            turtlebot3_home_service_challenge_tools
